FROM node:24-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy source code
COPY . .

# React usually runs on 3000
EXPOSE 3000

# This command starts the dev server (Change to "npm run preview" if using Vite)
CMD ["npm", "start"]